--상품 카테고리
CREATE TABLE PRODUCT_CATEGORY_TB(
	CATEGORY_NO NUMBER PRIMARY KEY,
	CATEGORY_NM VARCHAR2(30) NOT NULL,
	PARENT_CATEGORY_NO NUMBER,
	MBTI_NM VARCHAR2(1) DEFAULT NULL,
	CONSTRAINT CK_MBTI CHECK (MBTI_NAME IS NULL OR MBTI_NAME IN ('E','I','S','N','P','J','T','F'))
);
CREATE SEQUENCE PRODUCT_CATEGORY_SQ
INCREMENT BY 1
START WITH 1
CACHE 20;

-- 상품 이미지
CREATE TABLE PRODUCT_IMG_TB(
	IMG_NO	NUMBER	PRIMARY KEY,
	PRODUCT_NO	NUMBER	NOT NULL,
	IMG_URL	VARCHAR2(1000),
	IS_MAIN	VARCHAR2(1) DEFAULT 'N',
	CONSTRAINT FK_PRODUCT_IMG FOREIGN KEY (PRODUCT_NO) REFERENCES PRODUCT_TB(PRODUCT_NO),
	CONSTRAINT CK_MAIN CHECK (IS_MAIN IN ('N','Y'))
);
CREATE SEQUENCE PRODUCT_IMG_SQ
INCREMENT BY 1
START WITH 1
CACHE 50;

--상품
CREATE TABLE PRODUCT_TB (
	PRODUCT_NO	NUMBER	PRIMARY KEY,
	CATEGORY_NO	NUMBER	NOT NULL,
	SELLER_NO	NUMBER	NOT NULL,
	PRODUCT_NM	VARCHAR2(50),
	PRODUCT_PRICE	NUMBER,
	PRODUCT_STOCK	NUMBER,
	DETAIL_IMG_URL	VARCHAR2(1000),
	CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (CATEGORY_NO) REFERENCES PRODUCT_CATEGORY_TB(CATEGORY_NO),
    CONSTRAINT FK_PRODUCT_SELLER FOREIGN KEY (SELLER_NO) REFERENCES SELLER_TB(SELLER_NO)
);
CREATE SEQUENCE PRODUCT_SQ
INCREMENT BY 1
START WITH 1
CACHE 100;

--상품 옵션
CREATE TABLE PRODUCT_OPTION_TB (
	PRODUCT_OPTION_NO	NUMBER	PRIMARY KEY,
	PRODUCT_NO	NUMBER	NOT NULL,
	OPTION_NO	NUMBER	NOT NULL,
	CONSTRAINT FK_OPTION_NO FOREIGN KEY (OPTION_NO) REFERENCES OPTION_TB(OPTION_NO)
);
CREATE SEQUENCE PRODUCT_OPTION_SQ
START WITH 1
INCREMENT BY 1
CACHE 50;

--옵션
CREATE TABLE OPTION_TB(
	OPTION_NO NUMBER PRIMARY KEY,
	OPTION_CATEGORY_NO NUMBER NOT NULL,
	OPTION_NM VARCHAR2(20),
	CONSTRAINT FK_OPTION_CATEGORY_NO FOREIGN KEY(OPTION_CATEGORY_NO) REFERENCES OPTION_CATEGORY_TB(OPTION_CATEGORY_NO)
);
CREATE SEQUENCE OPTION_SQ
START WITH 1
INCREMENT BY 1
CACHE 20;

--옵션 카테고리
CREATE TABLE OPTION_CATEGORY_TB (
	OPTION_CATEGORY_NO	NUMBER	PRIMARY KEY,
	OPTION_CATEGORY_NM	VARCHAR2(20)
);
CREATE SEQUENCE OPTION_CATEGORY_SQ
START WITH 1
INCREMENT BY 1
CACHE 20;