-- 판매자
CREATE TABLE SELLER_TB(
	SELLER_NO NUMBER PRIMARY KEY,
	SELLER_ID VARCHAR2(30) UNIQUE NOT NULL,
	SELLER_PW VARCHAR2(255) NOT NULL,
	SELLER_NM VARCHAR2(20) NOT NULL,
	SELLER_TEL VARCHAR2(20) UNIQUE NOT NULL,
	SELLER_EMAIL VARCHAR2(30),
	BUSINESS_NO VARCHAR2(20) UNIQUE NOT NULL,
	BUSINESS_NM VARCHAR2(30) NOT NULL,
	BUSINESS_ADDR VARCHAR2(100) NOT NULL,
	IS_DELETED VARCHAR2(1) DEFAULT 'N',
	IS_ALLOWED VARCHAR2(1) DEFAULT 'N',
	JOINED_DATE DATE
);
CREATE SEQUENCE SELLER_SQ
START WITH 1
INCREMENT BY 1
CACHE 20;