name: "✨ Feature"
description: "새로운 기능 추가 요청"
title: "[FEATURE] "
labels: ["feature"]
assignees: []

body:
  - type: textarea
    attributes:
      label: "📄 설명"
      description: "새로운 기능에 대한 설명을 작성해 주세요."
      placeholder: "자세히 적을수록 좋습니다!"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "✅ 작업할 내용"
      description: "할 일을 체크박스 형태로 작성해주세요."
      placeholder: |
        - [ ] API 설계
        - [ ] 화면 UI 제작
        - [ ] 기능 연동
        - [ ] DB 생성
    validations:
      required: true

  - type: textarea
    attributes:
      label: "🙋🏻 참고 자료"
      description: "참고 자료가 있다면 작성해 주세요."
      placeholder: "링크, 문서, 이미지 등"
